#!/usr/bin/env python3
"""Generate src/hpack/tables.mojo from RFC 7541.

Parses the static header table (Appendix A) and the Huffman code table
(Appendix B) straight out of the RFC text so nothing is hand-transcribed.
Downloads the RFC on first run and caches it next to this script.
"""

import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent  # the mojo-http2 package
RFC_CACHE = Path(__file__).resolve().parent / ".rfc7541.txt"
RFC_URL = "https://www.rfc-editor.org/rfc/rfc7541.txt"
OUT = ROOT / "src" / "hpack" / "tables.mojo"


def rfc_text() -> str:
    if not RFC_CACHE.exists():
        RFC_CACHE.write_bytes(urllib.request.urlopen(RFC_URL).read())
    return RFC_CACHE.read_text()


def parse(txt: str):
    huff = sorted(
        (int(m.group(1)), int(m.group(2), 16), int(m.group(3)))
        for m in re.finditer(
            r"\(\s*(\d+)\)\s+\|[01|]+\s+([0-9a-f]+)\s+\[\s*(\d+)\]", txt
        )
    )
    assert [h[0] for h in huff] == list(range(257)), "Huffman parse failed"

    static: dict[int, tuple[str, str]] = {}
    for m in re.finditer(
        r"^\s*\|\s*(\d+)\s*\|\s*(\S+)\s*\|\s*([^|]*?)\s*\|\s*$", txt, re.M
    ):
        idx = int(m.group(1))
        if 1 <= idx <= 61 and idx not in static:
            static[idx] = (m.group(2), m.group(3))
    assert len(static) == 61, "static table parse failed"
    return huff, static


def main():
    huff, static = parse(rfc_text())
    codes = ", ".join(str(c) for _, c, _ in huff)
    lens = ", ".join(str(n) for _, _, n in huff)

    lines = [
        "# GENERATED by tools/gen_hpack_tables.py from RFC 7541 — do not edit.",
        "",
        '"""HPACK constant tables, generated from the text of',
        "[RFC 7541](https://www.rfc-editor.org/rfc/rfc7541).",
        "",
        "Regenerate with `pixi run gen-hpack`; do not edit by hand.",
        '"""',
        "",
        f"comptime HUFFMAN_CODE: Array[UInt32, 257] = [{codes}]",
        '"""Huffman codes (RFC 7541 Appendix B), right-aligned to the LSB.',
        "",
        'Index is the symbol: bytes 0-255, plus EOS at index 256.',
        '"""',
        "",
        f"comptime HUFFMAN_LEN: Array[UInt8, 257] = [{lens}]",
        '"""Bit length of each Huffman code in `HUFFMAN_CODE`."""',
        "",
        "comptime STATIC_TABLE_SIZE = 61",
        '"""Number of entries in the HPACK static header table."""',
    ]
    names = ", ".join(
        f'"{n}"' for n in [""] + [static[i][0] for i in range(1, 62)]
    )
    values = ", ".join(
        f'"{v}"' for v in [""] + [static[i][1] for i in range(1, 62)]
    )
    lines += [
        "",
        f"comptime STATIC_NAMES: Array[StaticString, 62] = [{names}]",
        '"""Names of the HPACK static header table, 1-indexed.',
        "",
        'From RFC 7541 Appendix A; index 0 is unused.',
        '"""',
        "",
        f"comptime STATIC_VALUES: Array[StaticString, 62] = [{values}]",
        '"""Values of the static header table, aligned with `STATIC_NAMES`."""',
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
